/*
 * S3 asset uploader REST API
 *
 * an S3 asset uploader API
 *
 * API version: 1.0.0
 * Contact: bill.hongwu.chen@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/v1/",
		Index,
	},

	Route{
		"AddAsset",
		strings.ToUpper("Post"),
		"/v1/asset",
		AddAsset,
	},

	Route{
		"DeleteAsset",
		strings.ToUpper("Delete"),
		"/v1/asset/{assetId}",
		DeleteAsset,
	},

	Route{
		"GetAssetById",
		strings.ToUpper("Get"),
		"/v1/asset/{assetId}",
		GetAssetById,
	},

	Route{
		"GetAssetListByStatus",
		strings.ToUpper("Get"),
		"/v1/asset",
		GetAssetListByStatus,
	},

	Route{
		"UpdateAssetUploadStatus",
		strings.ToUpper("Put"),
		"/v1/asset/{assetId}",
		UpdateAssetUploadStatus,
	},
}
